export const ERROR_CODES = [
  'VALIDATION_FAILED',
  'UNAUTHENTICATED',
  'MEMBERSHIP_REQUIRED',
  'ROLE_FORBIDDEN',
  'TENANT_RESOURCE_NOT_FOUND',
  'CONTACT_CONSENT_MISSING',
  'CONTACT_WITHDRAWN',
  'CONTACT_ARCHIVED',
  'CONTACT_DUPLICATE',
  'PHONE_INVALID',
  'SURVEY_NOT_OPEN',
  'SURVEY_CLOSED',
  'SURVEY_STATE_INVALID',
  'SURVEY_CONTENT_INVALID',
  'SURVEY_TIMING_INVALID',
  'AUDIENCE_EMPTY',
  'ANSWER_EDIT_EXPIRED',
  'ANSWER_STALE',
  'ANSWER_UNCHANGED',
  'QUESTION_OPTION_INVALID',
  'SELECTION_COUNT_INVALID',
  'ACTION_INVALID',
  'TEMPLATE_NOT_READY',
  'CONNECTION_DISABLED',
  'FLOW_NOT_READY',
  'SERVICE_WINDOW_CLOSED',
  'SEND_OUTCOME_UNKNOWN',
  'SEND_FAILED',
  'IDEMPOTENCY_CONFLICT',
  'IMPORT_VALIDATION_FAILED',
  'IMPORT_STATE_INVALID',
  'RESULTS_INSUFFICIENT_SAMPLE',
  'RESULTS_ALREADY_SHARED',
  'LAST_ADMIN_PROTECTED',
  'INVITATION_INVALID',
  'INVITATION_EMAIL_MISMATCH',
  'CONFIGURATION_INVALID',
  'LIVE_MODE_REQUIRED',
  'SIMULATOR_DISABLED',
  'SYNTHETIC_CONTACT',
  'RATE_LIMITED',
  'INTERNAL_ERROR',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export interface FieldError {
  path: string;
  message: string;
}

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  correlationId: string;
  fieldErrors?: FieldError[];
  details?: Record<string, unknown>;
}
