onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - nx
  - prisma
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
  - unrs-resolver
  - protobufjs
  - '@firebase/util'
  - '@scarf/scarf'
